name: CI CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: pull
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./shows-api
          file: ./shows-api/Dockerfile
          push: true
          tags: |
            fabioromao/testeapp:latest
            fabioromao/testeapp:${{ github.run_number }}
