name: deploy
on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v2

      #- name: Docker meta
      #  id: docker_meta
      #  uses: crazy-max/ghaction-docker-meta@v1
      #  with:
      #    images: romaofr/dummy-logger:1.0
      #    tags-sha: true
      
      #- name: QEMU
      #  uses: docker/setup-qemu-action@v1

      #- name: Docker Buildx
      #  uses: docker/setup-buildx-action

      #- name: Docker login docker hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_PWD }}
      #    password: ${{ secrets.DOCKERHUB_USER }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

#      - name: Setup kubectl
#        uses: matootie/dokube@v1.3.2
#        with:
