name: CI CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: pull
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrects.DOCKERHUB_USER }}
          password: ${{ secrects.DOCKERHUB_PWD }}

      #- name: Docker Build and Push
      #  uses: docke/build-push-action@v2.7.0
      #  with:
      #    context: app/app
      #    file: app/app/Dockerfile
      #    push: true
      #    tags: |
      #      fabioromao/testeapp:latest
      #      fabioromao/testeapp:${{ github.run_number }}
