name: deploy
on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    #env:
    #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_KEY_ID }}
    #  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET }}
    

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: romaofr/dummy-logger:1.0
          tags-sha: true
      
      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Buildx
        uses: docker/setup-buildx-action

      - name: Docker login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.tokendhub }}

      - name: Docker Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./authp/auth
          file: ./authp/auth/Dockerfile
          platforms: linux/amd64,linux/arm64,linux386
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

#      - name: Setup kubectl
#        uses: matootie/dokube@v1.3.2
#        with:
